#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -n "$PREFIX" ] && [ -d "$PREFIX/bin" ] && [ ! -f "$PREFIX/bin/kiki" ]; then
  cat << EOF > "$PREFIX/bin/kiki"
#!/usr/bin/env bash
exec node "$DIR/kiki.js" "\$@"
EOF
  chmod +x "$PREFIX/bin/kiki"
  cp "$PREFIX/bin/kiki" "$PREFIX/bin/fk" 2>/dev/null || true
fi

exec node "$DIR/kiki.js" "$@"
